import{i as l,S as w,a as v}from"./assets/vendor-CMSP9hSB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="data:image/svg+xml,%3c?xml%20version='1.0'%20encoding='utf-8'?%3e%3c!--%20Uploaded%20to:%20SVG%20Repo,%20www.svgrepo.com,%20Generator:%20SVG%20Repo%20Mixer%20Tools%20--%3e%3csvg%20width='800px'%20height='800px'%20viewBox='0%200%2024%2024'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M2.20164%2018.4695L10.1643%204.00506C10.9021%202.66498%2013.0979%202.66498%2013.8357%204.00506L21.7984%2018.4695C22.4443%2019.6428%2021.4598%2021%2019.9627%2021H4.0373C2.54022%2021%201.55571%2019.6428%202.20164%2018.4695Z'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3cpath%20d='M12%209V13'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3cpath%20d='M12%2017.0195V17'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3c/svg%3e",u=document.querySelector(".gallery"),k=document.querySelector(".load"),f=document.querySelector(".add-more-button"),x={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:d,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};function h(r){r.insertAdjacentHTML("beforeend",'<p class="loading-text">Wait, the image is loaded</p><span class="loader"></span>'),f.classList.add("hide")}function y(r){const o=r.querySelector(".loading-text"),n=r.querySelector(".loader");o&&o.remove(),n&&n.remove(),f.classList.remove("hide")}function q(r){const{hits:o}=r;if(o.length===0){l.show({...x,message:"Sorry, there are no images matching your search query. Please, try again!"}),u.innerHTML="";return}const n=o.map(e=>`<li class='gallery__item'>
        <a class='gallery__link' href="${e.largeImageURL}">
        <img class='gallery__img' src="${e.webformatURL}" alt="${e.tags}" />
          <div class="grid">
            <p>Likes</p>
            <p>Views</p>
            <p>Comment</p>
            <p>Downloads</p>
            <span>${e.likes}</span>
            <span>${e.views}</span>
            <span>${e.comments}</span>
            <span>${e.downloads}</span>
          </div>
        </a>
      </li>`).join(" ");y(k),u.insertAdjacentHTML("beforeend",n),new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const p=document.querySelector(".gallery"),m=document.querySelector(".load"),M=document.querySelector(".add-more-button"),$={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:d,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};let s=1,g=30;function C(){s=1}function F(){s+=1}function O(r){y(r),r.insertAdjacentHTML("beforeend",`<p class="loading-text">We're sorry, but you've reached the end of search results .</p>`),M.classList.add("hide")}async function L(r){const o="48927114-800727f947c08d044ecb8ca31",n=encodeURIComponent(r);s===1&&(p.innerHTML="");const e=`https://pixabay.com/api/?${new URLSearchParams({key:o,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:g})}`;try{const{data:t}=await v.get(e);if(q(t),t.totalHits<s*g){O(m);return}if(s>=2){const S=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:S.height*2,behavior:"smooth"})}}catch(t){console.error(t),p.innerHTML="",m.innerHTML="",l.show({...$,message:"Sorry, an error happened. Try again"});return}}const P=document.querySelector(".gallery"),b=document.querySelector(".load"),I=document.querySelector(".add-more-button"),A=document.querySelector(".form"),c=document.querySelector(".user-input"),R={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:d,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};A.addEventListener("submit",r=>{r.preventDefault();let o=c.value.trim();if(!o){l.show({...R,message:"Please enter the search query"});return}P.innerHTML="",C(),h(b),L(o),c.value=""});I.addEventListener("click",r=>{let o=c.value.trim();F(),h(b),L(o)});
//# sourceMappingURL=index.js.map
