import{i as d,S as x,a as M}from"./assets/vendor-CMSP9hSB.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="data:image/svg+xml,%3c?xml%20version='1.0'%20encoding='utf-8'?%3e%3c!--%20Uploaded%20to:%20SVG%20Repo,%20www.svgrepo.com,%20Generator:%20SVG%20Repo%20Mixer%20Tools%20--%3e%3csvg%20width='800px'%20height='800px'%20viewBox='0%200%2024%2024'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M2.20164%2018.4695L10.1643%204.00506C10.9021%202.66498%2013.0979%202.66498%2013.8357%204.00506L21.7984%2018.4695C22.4443%2019.6428%2021.4598%2021%2019.9627%2021H4.0373C2.54022%2021%201.55571%2019.6428%202.20164%2018.4695Z'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3cpath%20d='M12%209V13'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3cpath%20d='M12%2017.0195V17'%20stroke='%23000000'%20stroke-width='2'%20stroke-linecap='round'%20stroke-linejoin='round'/%3e%3c/svg%3e",c=document.querySelector(".gallery"),$=document.querySelector(".load"),u=document.querySelector(".add-more-button"),C={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:f,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};function m(o){o?o.insertAdjacentHTML("beforeend",'<p class="loading-text">Wait, the image is loaded</p><span class="loader"></span>'):console.warn("daddyElement not found"),u?u.classList.add("hide"):console.warn("addMoreButton element not found")}function p(o){if(o){const n=o.querySelector(".loading-text"),r=o.querySelector(".loader");n&&n.remove(),r&&r.remove()}else console.warn("daddyElement not found");u?u.classList.remove("hide"):console.warn("addMoreButton element not found")}function O(o){const{hits:n}=o;if(n.length===0){d.show({...C,message:"Sorry, there are no images matching your search query. Please, try again!"}),c.innerHTML="";return}const r=n.map(e=>`<li class='gallery__item'>
        <a class='gallery__link' href="${e.largeImageURL}">
        <img class='gallery__img' src="${e.webformatURL}" alt="${e.tags}" />
          <div class="grid">
            <p>Likes</p>
            <p>Views</p>
            <p>Comment</p>
            <p>Downloads</p>
            <span>${e.likes}</span>
            <span>${e.views}</span>
            <span>${e.comments}</span>
            <span>${e.downloads}</span>
          </div>
        </a>
      </li>`).join(" ");p($),c?c.insertAdjacentHTML("beforeend",r):console.warn("Gallery box not found");const a=new x(".gallery a",{captionsData:"alt",captionDelay:250});c.querySelector(".gallery__item")&&a.refresh()}const P=document.querySelector(".gallery"),g=document.querySelector(".load"),y=document.querySelector(".add-more-button"),F={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:f,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};let l=1,h=15;function _(){l=1}function B(){l+=1}function I(o){o?o.insertAdjacentHTML("beforeend",`<p class="loading-text">We're sorry, but you've reached the end of search results.</p>`):console.warn("daddyElement not found"),y?y.classList.add("hide"):console.warn("addMoreButton element not found")}async function w(o){const n="48621636-2f551eda37f80f5c324cc68cd",r=encodeURIComponent(o),e=`https://pixabay.com/api/?${new URLSearchParams({key:n,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:h})}`;try{const{data:t}=await M.get(e);if(O(t),t.totalHits<l*h){I(g);return}if(l>=2){const s=document.querySelector(".gallery__item");if(s){const q=s.getBoundingClientRect();window.scrollBy({top:q.height*2,behavior:"smooth"})}else console.warn("No gallery items found for scrolling")}}catch(t){console.error(t),P.innerHTML="",g.innerHTML="",d.show({...F,message:"Sorry, an error happened. Try again"});return}}const L=document.querySelector(".gallery"),i=document.querySelector(".load"),S=document.querySelector(".add-more-button"),b=document.querySelector(".form"),v=document.querySelector(".user-input"),k={messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:f,transitionIn:"bounceInLeft",position:"topRight",displayMode:"replace",closeOnClick:!0};if(!b||!v||!L||!i||!S)console.error("One or more required elements not found in DOM");else{let o="";b.addEventListener("submit",n=>{n.preventDefault();const r=v.value.trim();if(!r){d.show({...k,message:"Please enter the search query"});return}o=r,L.innerHTML="",_(),m(i),w(o).finally(()=>{p(i)})}),S.addEventListener("click",n=>{if(!o){d.show({...k,message:"No query to load more images. Please search again."});return}B(),m(i),w(o).finally(()=>{p(i)})})}
//# sourceMappingURL=index.js.map
